### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by sijo-vijayan** [sgress454/sailsChat#2]
I go the following error while installing dependencies 

ti@72:/var/www/projects/sailsChat$ sudo npm install
npm ERR! git rev-list -n1 v0.10: fatal: ambiguous argument 'v0.10': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 v0.10: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 v0.10: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 v0.10: 
npm ERR! Linux 3.5.0-54-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 v0.10
npm ERR! fatal: ambiguous argument 'v0.10': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/projects/sailsChat/npm-debug.log

**Comment by sgress454** [comment]
Yikes!  Thanks for pointing this out, @sijo-vijayan.  Fixed the package.json, should install fine now.  I'd just `rm -rf node_modules` and `npm install` again.

**Comment by sijo-vijayan** [comment]
Now it showing another error

ti@72:/var/www/projects/chat1$ sails lift

info: Starting app...

module.js:327
    throw err;
    ^

Error: Cannot find module 'express/node_modules/connect'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/projects/chat1/node_modules/sails/lib/hooks/session/index.js:10:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /var/www/projects/chat1/node_modules/sails/lib/app/configuration/index.js:54:28
    at Function.reduce (/var/www/projects/chat1/node_modules/sails/node_modules/lodash/dist/lodash.js:3735:25)
    at Configuration.defaultConfig (/var/www/projects/chat1/node_modules/sails/lib/app/configuration/index.js:53:18)
    at Configuration.bound [as defaults] (/var/www/projects/chat1/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Array.async.auto.mixinDefaults (/var/www/projects/chat1/node_modules/sails/lib/app/configuration/load.js:136:41)

**Comment by sgress454** [comment]
Hm, that sounds like an old version of Sails.  Did you wipe your `node_modules` first?  Also try `npm cache clean` before doing `npm install`.

**Comment by sijo-vijayan** [comment]
Yes, Done and updated the sails.io.js in my client side using "sails generate sails.io.js --force" command.

Now the first request is processing, but the sails process stops in the in server side due to the error given below

/var/www/projects/chat/config/sockets.js:33
        session.save();
                ^

TypeError: session.save is not a function
  at /var/www/projects/chat/config/sockets.js:33:17
  at wrapper (/var/www/projects/chat/node_modules/waterline/node_modules/lodash/index.js:3602:19)
  at applyInOriginalCtx (/var/www/projects/chat/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
  at wrappedCallback (/var/www/projects/chat/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
  at callback.success (/var/www/projects/chat/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
  at _switch (/var/www/projects/chat/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
  at /var/www/projects/chat/node_modules/waterline/lib/waterline/query/dql/create.js:242:9
  at /var/www/projects/chat/node_modules/waterline/node_modules/async/lib/async.js:49:16
  at /var/www/projects/chat/node_modules/waterline/node_modules/async/lib/async.js:263:32
  at /var/www/projects/chat/node_modules/waterline/node_modules/async/lib/async.js:40:16
  at bound.<anonymous> (/var/www/projects/chat/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
  at fn (/var/www/projects/chat/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:60:10)
  at /var/www/projects/chat/node_modules/waterline/node_modules/async/lib/async.js:162:20
  at iterate (/var/www/projects/chat/node_modules/waterline/node_modules/async/lib/async.js:256:13)
  at Object.async.forEachOfSeries.async.eachOfSeries (/var/www/projects/chat/node_modules/waterline/node_modules/async/lib/async.js:275:9)
  at Object.async.forEachSeries.async.eachSeries (/var/www/projects/chat/node_modules/waterline/node_modules/async/lib/async.js:211:22)
  at Object.runner.afterCreate (/var/www/projects/chat/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:63:9)
  at after (/var/www/projects/chat/node_modules/waterline/lib/waterline/query/dql/create.js:237:17)
  at /var/www/projects/chat/node_modules/waterline/lib/waterline/query/dql/create.js:224:67
  at wrapper (/var/www/projects/chat/node_modules/waterline/node_modules/lodash/index.js:3602:19)
  at applyInOriginalCtx (/var/www/projects/chat/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
  at wrappedCallback (/var/www/projects/chat/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
  at callback.success (/var/www/projects/chat/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
  at _switch (/var/www/projects/chat/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
  at afterwards (/var/www/projects/chat/node_modules/waterline/lib/waterline/adapter/dql.js:89:19)
  at wrapper (/var/www/projects/chat/node_modules/waterline/node_modules/lodash/index.js:3602:19)
  at applyInOriginalCtx (/var/www/projects/chat/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
  at wrappedCallback (/var/www/projects/chat/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
  at callback.success (/var/www/projects/chat/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
  at _switch (/var/www/projects/chat/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
  at [object Object]._onTimeout (/var/www/projects/chat/node_modules/sails-disk/lib/adapter.js:179:10)
  at Timer.listOnTimeout (timers.js:92:15)

**Comment by sgress454** [comment]
Ah, so I just realized which branch we're on.  You should try https://github.com/balderdashy/sailsChat, it's more up-to-date.  I'll merge that one back in to this just, because I realize there's still a lot of links to this one out there.

**Comment by sijo-vijayan** [comment]
ohh, So it is wrong place, Google bring me here. Let me clone the latest version from that url.

https://github.com/balderdashy/sailsChat
In this repo, sailsjs version is ~0.12.3. Can i use sails 0.11.3 version instead without changing the codes ?

**Comment by sgress454** [comment]
> In this repo, sailsjs version is ~0.12.3. Can i use sails 0.11.3 version instead without changing the codes ?

You should be able to, let me know if there's any problems!

**Comment by sijo-vijayan** [comment]
Wow, Now it working perfectly with sails 0.12.3 and 0.11.3, but showing an Error and waning given below

warn: Socket disconnected, but session could not be loaded to pass to configured disconnect handler: `sails.config.sockets.afterDisconnect()`.  Will pass a fake, empty session as argument to lifecycle callback.  Details:
 Error: Session could not be loaded


But, It working without any issues.

**Comment by sijo-vijayan** [comment]
Also, I would like to know, How can we switch to mysql database instead of the current storage ?

**Comment by sgress454** [comment]
That warning usually means you had a browser tab/window open pointing at the app before you actually started the server (most likely because you stopped Sails and then restarted it with the tab still open).  The socket re-connects and Sails no longer has any session info associated with it.

Re: MySQL, it should be no different than any other Sails app -- just create a connection for it in `config/connections.js` and set the default connection in `config/models.js` to use it.  See the [`connections.js` docs](http://sailsjs.org/documentation/reference/configuration/sails-config-connections) for more info.

**Comment by sijo-vijayan** [comment]
Yes, you are correct.
Thanks for the help :) :+1:
